In [2]:
import sys 
import tensorflow as tf 

In [3]:
# get the minst dataset 
mnist = tf.keras.datasets.mnist

In [56]:
# create training and test sets 
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [57]:
# examine first image
x_train[:1]

array([[[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           3,  18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,
           0,   0,   0

In [58]:
# examine first label 
y_train[:1]

array([5], dtype=uint8)

In [59]:
# This image belongs to digit 5... Now divide each of the the array with 255 so that 
# we have vcalues between 0 and 1 
x_train, x_test = x_train / 255.0, x_test / 255.0 

In [83]:
# convert the categorical data in the lable to columns so that we have 0 or 1 for each digit
y_train = tf.keras.utils.to_categorical(y_train)
y_train[:1]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [84]:
y_test = tf.keras.utils.to_categorical(y_test)

In [85]:
x_train.shape

(60000, 28, 28, 1)

# this means there are 60000 images of 28x28 pixels 

Initially, these images are often represented as a collection of 2D arrays. However, most deep learning models, especially Convolutional Neural Networks (CNNs), expect input data in a specific format, typically a 4D tensor.

The reshaping process transforms the data into a format of (number of samples, height, width, number of channels). For MNIST, this translates to (60000, 28, 28, 1) for the training set, where 60000 is the number of training samples, 28x28 is the image size, and 1 represents the single grayscale channel. 

In [86]:
# reshape the dataset 
x_train = x_train.reshape(
    x_train.shape[0], x_train.shape[1], x_train.shape[2], 1
)
x_train.shape

(60000, 28, 28, 1)

In [87]:
# reshape the dataset 
x_test = x_test.reshape(
    x_test.shape[0], x_test.shape[1], x_test.shape[2], 1
)
x_test.shape

(10000, 28, 28, 1)

In [88]:
model = tf.keras.models.Sequential() 
model.add(tf.keras.layers.Input(shape=(28, 28, 1)))


In [89]:
# Convolutional layer. Learn 32 filters using a 3x3 kernel
model.add(tf.keras.layers.Conv2D(
        32, (3, 3), activation="relu"
    ))

In [90]:
# Max-pooling layer, using 2x2 pool size
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))

In [91]:
model.add(tf.keras.layers.Flatten())

In [92]:
# Add an output layer with output units for all 10 digits
model.add(tf.keras.layers.Dense(10, activation="softmax"))

In [93]:
# Train neural network
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_9 (Conv2D)               │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 5408)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 10)             │        54,090 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54,410 (212.54 KB)

 Trainable params: 54,410 (212.54 KB)

 Non-trainable params: 0 (0.00 B)

In [99]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9958 - loss: 0.0138
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9966 - loss: 0.0130
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9970 - loss: 0.0101
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9975 - loss: 0.0087
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9984 - loss: 0.0068
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9984 - loss: 0.0063
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9987 - loss: 0.0050
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9985 - loss: 0.0056
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9992 - loss: 0.0036
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9990 - loss: 0.0037


In [100]:
# Evaluate neural network performance
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9844 - loss: 0.0700


[0.07000771164894104, 0.9843999743461609]

In [101]:
# save the model for future iterations
model.save("minst_model.h5")