Get Dataset from - https://archive.ics.uci.edu/dataset/151/connectionist+bench+sonar+mines+vs+rocks

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv('data/video20/sonar.all-data', header=None)
df.sample(5)

0       1       2       3       4       5       6       7       8   \
165  0.0221  0.0065  0.0164  0.0487  0.0519  0.0849  0.0812  0.1833  0.2228   
25   0.0201  0.0026  0.0138  0.0062  0.0133  0.0151  0.0541  0.0210  0.0505   
106  0.0331  0.0423  0.0474  0.0818  0.0835  0.0756  0.0374  0.0961  0.0548   
152  0.0131  0.0201  0.0045  0.0217  0.0230  0.0481  0.0742  0.0333  0.1369   
164  0.0163  0.0198  0.0202  0.0386  0.0752  0.1444  0.1487  0.1484  0.2442   

         9   ...      51      52      53      54      55      56      57  \
165  0.1810  ...  0.0089  0.0051  0.0015  0.0075  0.0058  0.0016  0.0070   
25   0.1097  ...  0.0108  0.0070  0.0063  0.0030  0.0011  0.0007  0.0024   
106  0.0193  ...  0.0078  0.0174  0.0176  0.0038  0.0129  0.0066  0.0044   
152  0.2079  ...  0.0168  0.0086  0.0045  0.0062  0.0065  0.0030  0.0066   
164  0.2822  ...  0.0077  0.0026  0.0031  0.0083  0.0020  0.0084  0.0108   

         58      59  60  
165  0.0074  0.0038   M  
25   0.0057  0.0044   R  
106  0.0134  0.0092   M  
152  0.0029  0.0053   M  
164  0.0083  0.0033   M  

[5 rows x 61 columns]

In [3]:
df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [4]:
X = df.drop(60, axis=1)
y = df[60]


In [5]:
# y is a categorical data... convert this to 0 and 1 
y = pd.get_dummies(y, drop_first=True)

R
0  True
1  True
2  True
3  True
4  True
5  True
6  True
7  True
8  True
9  True

In [6]:
y.sample(5)

R
13    True
31    True
119  False
122  False
133  False

In [7]:
# separate the test and training set 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [8]:
# create model 
from tensorflow import keras 
import tensorflow as tf 

In [9]:
X_train.shape

(166, 60)

In [17]:
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

In [18]:
# create model 
modela = keras.models.Sequential()
modela.add(keras.layers.Input(shape=[60, ]))
modela.add(keras.layers.Dense(30, activation="relu"))
modela.add(keras.layers.Dense(15, activation="relu"))
modela.add(keras.layers.Dense(1, activation="sigmoid"))

# compile the model 
modela.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
modela.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │           465 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,311 (9.03 KB)

 Trainable params: 2,311 (9.03 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
# train the modela as minibatch of 8 
with tf.device('/CPU:0'):
    modela.fit(X, y, epochs=100, batch_size=8)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4702 - loss: 0.7411 
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6538 - loss: 0.6703
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6956 - loss: 0.6552
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7622 - loss: 0.6387
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8195 - loss: 0.6185
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8179 - loss: 0.5949
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8178 - loss: 0.5690
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8228 - loss: 0.5445
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8179 - loss: 0.5215
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8188 - loss: 0.5015
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8194 - loss: 0.4825
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy

In [22]:
# evaluate the model using test set 
modela.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7946 - loss: 1.4735 


[1.5008022785186768, 0.7857142686843872]

```
Clearly model is overfitting here. Let's use the Dropout strategy 

In [47]:
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

In [48]:
# create model 
modelb = keras.models.Sequential()
modelb.add(keras.layers.Input(shape=[60, ]))
modelb.add(keras.layers.Dense(60, activation="relu"))
modelb.add(keras.layers.Dropout(0.5))
modelb.add(keras.layers.Dense(30, activation="relu"))
modelb.add(keras.layers.Dropout(0.5))
modelb.add(keras.layers.Dense(15, activation="relu"))
modelb.add(keras.layers.Dropout(0.5))
modelb.add(keras.layers.Dense(1, activation="sigmoid"))

# compile the model 
modelb.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [49]:
modelb.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 60)             │         3,660 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 60)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 30)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 15)             │           465 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 15)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,971 (23.32 KB)

 Trainable params: 5,971 (23.32 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
# train the modela as minibatch of 8 
with tf.device('/CPU:0'):
    modelb.fit(X, y, epochs=100, batch_size=8)

Epoch 1/100


26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4672 - loss: 0.7977 
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5527 - loss: 0.6941
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5044 - loss: 0.7038
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5193 - loss: 0.6919
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4260 - loss: 0.7045   
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4635 - loss: 0.7059
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6053 - loss: 0.6857
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5548 - loss: 0.6747
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5426 - loss: 0.6928
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6235 - loss: 0.6610
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5100 - loss: 0.7091
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5846 

In [51]:
modelb.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7842 - loss: 2.8816 


[2.7348453998565674, 0.7857142686843872]

``` 
Still overfitting lets use model created in the video

In [45]:
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

In [52]:
modelc = keras.models.Sequential([
    keras.layers.Dense(60, input_dim=60, activation="relu"), 
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation="relu"), 
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation="relu"), 
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation="sigmoid")
])

modelc.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
modelc.summary()

/Users/rohitabhishek/miniconda3/envs/mlenv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 60)             │         3,660 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 60)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 30)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 15)             │           465 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 15)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,971 (23.32 KB)

 Trainable params: 5,971 (23.32 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
# train the modela as minibatch of 8 
with tf.device('/CPU:0'):
    modelc.fit(X, y, epochs=100, batch_size=8)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4686 - loss: 0.7157 
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5513 - loss: 0.7214
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5280 - loss: 0.7101
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4393 - loss: 0.7527
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5263 - loss: 0.6902
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5235 - loss: 0.6932
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5464 - loss: 0.6881
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5311 - loss: 0.6695
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5691 - loss: 0.6566
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5691 - loss: 0.6790
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5470 - loss: 0.6861
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy

In [54]:
modelc.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7316 - loss: 2.4274 


[2.2620151042938232, 0.738095223903656]

In [56]:
# lets make predictions 
y_pred = modelb.predict(X_test)

y_pred = np.round(y_pred)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


In [57]:
y_pred

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [58]:
# lets create confusion martix 
cm = tf.math.confusion_matrix(y_test, y_pred.reshape(-1))

In [59]:
cm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19,  1],
       [ 8, 14]], dtype=int32)>